#!/bin/bash

ls | grep -Ev '^(pass\.txt|update)$' | xargs --no-run-if-empty rm -rf
wget https://downloads.nordcdn.com/configs/archives/servers/ovpn.zip
unzip ovpn.zip
mv ovpn_udp/au* .
rm -rf ovpn.zip ovpn_tcp ovpn_udp
sed -i 's/auth-user-pass/auth-user-pass pass.txt/' *.ovpn
